blank_issues_enabled: true
contact_links:
  - name: "Climakitae Documentation"
    url: "https://cal-adapt.github.io/climakitae/dev/"
    about: "Documentation for the Cal-Adapt Analytics Engine"
  - name: "Climakitae Contribution Guidelines"
    url: "https://cal-adapt.github.io/climakitae/dev/contributing/"
    about: "Guidelines for contributing to the Cal-Adapt Analytics Engine"