# Workflow file for continuous integration
# Conda environment is caches to avoid long wait times for CI
# Based on code from: https://github.com/epassaro/cache-conda-envs/blob/main/.github/workflows/ci.yml
# Based on code from: https://github.com/marketplace/actions/setup-miniconda
# Added to Test commit workflow


name: Test macOS
on: [push]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: | 
          brew install llvm@14
          export PATH="/opt/homebrew/opt/llvm@14/bin:$PATH"
          export LLVM_CONFIG="/opt/homebrew/opt/llvm@14/bin/llvm-config"
          pip install -U pip uv
          uv venv --python 3.11
          source .venv/bin/activate
          uv sync
